name: Deployment-Workflow
on: push
jobs:
  Code-Test-Build:
      runs-on: ubuntu-latest
      steps:
        - name: Code-Checkout
          uses: actions/checkout@v6
        - name: Dependencies-Install
          run: npm ci
        - name: Lint-Test
          run: npm run lint
        - name: Tests
          run: npm run test
        - name: Code-build
          run: npm run build
  Deploy:
    runs-on: ubuntu-latest
    needs: Code-Test-Build
    steps:
      - name: Run deployment
        run: echo "Deploying..."
