name: Deployment-Workflow
on: push
jobs:
  Lint-Test:
      runs-on: ubuntu-latest
      steps:
        - name: Run Lint test
          run: npm run lint
  Test:
     runs-on: ubuntu-latest
     needs: Lint-Test
     steps:
       - name: Run Tests
         run: npm run test
  Build:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - name: Run build
        run: npm run build
  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Run deployment
        run: echo "Deploying..."
